os: windows

language: node_js

node_js:
- '10'

install:
  - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
  - choco install iisexpress
  - choco install jdk11
  - choco install googlechrome --ignore-checksums
  - export PATH=$PATH:"/c/Program Files/Java/jdk-11.0.2/bin"
  - export PATH=$PATH:"C:\Program Files\Java\jdk-11.0.2\bin"
  - PowerShell -Command 'refreshenv'
  - java -version
  

script:
  - cd e2e-tests
  - npm install
  - npm run pretest
  - start 'C:\\Program\ Files\\IIS\ Express\\iisexpress.exe /path:C:\\Users\\travis\\build\\okta\\samples-aspnet-webforms\\okta-hosted-login\\dist\\okta-aspnet-webforms-example'
  - npm run test:okta-hosted-login
  - PowerShell -Command 'TASKKILL /F /IM iisexpress.exe'
