version: 2.1

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.8

workflows:
  # See OKTA-624823
  semgrep:
    jobs:
      - general-platform-helpers/job-semgrep-prepare:
          name: semgrep-prepare
      - general-platform-helpers/job-semgrep-scan:
          name: "Scan with Semgrep"
          requires:
            - semgrep-prepare