version: 2.1

orbs:
  windows: circleci/windows@5.0
  general-platform-helpers: okta/general-platform-helpers@1.9
  platform-helpers: okta/platform-helpers@1
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@5.1

jobs:
  build:
    executor:
      name: windows/default
    steps:
      - checkout

      - run:
          name: "Install required components"
          command: |
              choco install -y dotnetcore-sdk
              
      - run: dotnet --version

      - run:
          name: build okta-hosted-login to scan
          command: ./okta-hosted-login/build.sh

      - run:
          name: build self-hosted-login to scan
          command: ./self-hosted-login/build.sh

      - run:
          name: build social-login to scan
          command: ./social-login/build.sh

      - persist_to_workspace:
          root: ~/project
          paths:
            - src
            - .git
            - okta-hosted-login
            - self-hosted-login
            - social-login

      - run:
          name: Install Python
          command: |
            choco install python --version=3.9.0 -y
            python --version
            python -m pip install --upgrade pip

      - run:
          name: Download Reverse Labs Scanner
          command: |
            curl.exe https://dso-resources.oktasecurity.com/scanner  -H "x-api-key: $env:DSO_RLSECURE_TOKEN" -o rl_wrapper-0.0.2+35ababa-py3-none-any.whl

      - run:
          name: Install RL Wrapper
          command: |
            pip install ./rl_wrapper-0.0.2+35ababa-py3-none-any.whl

  prep-packages-config-for-snyk:
    docker:
      - image: cimg/python:3.10
    parameters:
      dotnet-target-framework-version:
        default: net50
        description: The .NET targeting version to set in packages.config
        type: string
      package-id:
        default: Cake MSBuildTasks nlohmann.json
        description: Package IDs to patch in packages.config
        type: string
    steps:
      - attach_workspace:
          at: ~/project
      - run:
            name: Install xmlstarlet
            command: |
              sudo apt-get update
              sudo apt-get install -y xmlstarlet
      - run:
          name: Patch packages.config for Snyk compatibility
          command: |
            for n in ${PACKAGE_ID}; do
              find ~/project -name "packages.config" -type f  \
                -exec xmlstarlet ed --inplace -i "//package[@id=\"$n\"][not(@targetFramework)]" \
                -t attr -n "targetFramework" -v ${DOTNET_TARGET_FRAMEWORK_VERSION} {} \; \
                -exec xmlstarlet ed --inplace -u "//package[@id=\"$n\" and @targetFramework='native']/@targetFramework" \
                -v ${DOTNET_TARGET_FRAMEWORK_VERSION} {} \;
            done
          environment:
            DOTNET_TARGET_FRAMEWORK_VERSION: << parameters.dotnet-target-framework-version >>
            PACKAGE_ID: << parameters.package-id >>

  reversinglabs-scan:
    docker:
      - image: cimg/python:3.10
    steps:
      - run:
          command: >
            echo "export ARTIFACT_DIR=$(echo
            "${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/path/to/my/directory")" >>
            "$BASH_ENV"

            echo "export ARTIFACT_COMMIT=$(echo "${CIRCLE_SHA1:0:8}")" >>
            "$BASH_ENV"

            source "$BASH_ENV"
          name: Set environment variables
      - platform-helpers/step-reversinglabs-scan:
          artifact-commit: $ARTIFACT_COMMIT
          artifact-dir: $ARTIFACT_DIR
          artifact-name: my-artifact-name

  snyk-scan:
    docker:
      - image: cimg/python:3.10
    steps:
      - attach_workspace:
          at: ~/project
      - general-platform-helpers/step-load-dependencies
      - general-platform-helpers/step-run-snyk-monitor:
          scan-all-projects: true
          skip-unresolved: false
          run-on-non-main: true
          detection-depth: 4

workflows:
  "Circle CI Tests":
    jobs:
      - build:
          context:
            - static-analysis
      - prep-packages-config-for-snyk:
          name: patch-configs
          context:
            - static-analysis
          requires:
            - build
      - snyk-scan:
          name: execute-snyk
          context:
            - static-analysis
          requires:
            - patch-configs
