# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  windows: circleci/windows@5.0
  general-platform-helpers: okta/general-platform-helpers@1.9
  platform-helpers: okta/platform-helpers@1
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@5.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run: dotnet --version

      - run: 
          name: build okta-hosted-login to scan
          command: ./okta-hosted-login/build.sh

      - run: 
          name: build self-hosted-login to scan
          command: ./self-hosted-login/build.sh

      - run: 
          name: build social-login to scan
          command: ./social-login/build.sh
        
      - run:
          name: Install Python
          command: |
            choco install python --version=3.9.0 -y
            python --version
            python -m pip install --upgrade pip
  
      - run:
          name: Download Reverse Labs Scanner
          command: |
            curl.exe https://dso-resources.oktasecurity.com/scanner  -H "x-api-key: $env:DSO_RLSECURE_TOKEN" -o rl_wrapper-0.0.2+35ababa-py3-none-any.whl
      - run:
          name: Install RL Wrapper
          command: |
            pip install ./rl_wrapper-0.0.2+35ababa-py3-none-any.whl
  
      - run:
          name: Run Reversing Labs Wrapper Scanner
          command: |
            rl-wrapper \
              --artifact ${CIRCLE_WORKING_DIRECTORY/#\~/$HOME} \
              --name $CIRCLE_PROJECT_REPONAME\
              --version $CIRCLE_SHA1\
              --repository $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
              --commit $CIRCLE_SHA1 \
              --build-env "circleci" \
              --suppress_output
  
  snyk-scan:
    docker:
      - image: cimg/python:3.10

    steps:
      - attach_workspace: # Allows for sharing of build-workspace (containing downloaded dependencies) (optional)
          at: ~/project
      - general-platform-helpers/step-load-dependencies
      - general-platform-helpers/step-run-snyk-monitor:
          scan-all-projects: true
          skip-unresolved: false
          run-on-non-main: true
          detection-depth: 4


workflows:
  "Circle CI Tests":
    jobs:
      - build
      - snyk-scan:
          name: execute-snyk
          context:
            - static-analysis
          requires:
            - build
  "Semgrep":
    jobs:
      - platform-helpers/job-semgrep-scan:
          context:
            - static-analysis
          name: "Scan with Semgrep"